services:
  db:
    container_name: db-salesapi
    image: mysql:9.1.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}

volumes:
  mysql:
